FROM debian:buster-slim
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

COPY gorse-master /usr/bin/gorse-master

ENV USER root

ENTRYPOINT ["/usr/bin/gorse-master", "-c", "/etc/gorse/config.toml"]
